fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    sysctl:
      repo: "https://github.com/kodguru/puppet-sysctl.git"
    mount_core:
      repo: "https://github.com/puppetlabs/puppetlabs-mount_core.git"
